package spgui.widgets.VDGUI

import scalacss.DevDefaults._
import japgolly.scalajs.react.vdom.html_<^._
import scalacss.internal.DslBase.ToStyle
import scalacss.internal.mutable.StyleSheet
import scalacss.internal.{Style, StyleA}

object CSSHelpers extends StyleSheet.Standalone {
  implicit def toHtml(a: StyleA): TagMod = ^.className := a.htmlClass

  object Child {
    val child: CSSHelpers.Child.type = Child
    def childStyle(n: String)(t: ToStyle*): Style.UnsafeExt = dsl.unsafeChild(n)(t:_*)

    def wbr(t: ToStyle*): Style.UnsafeExt = childStyle("wbr")(t:_*)
    def video(t: ToStyle*): Style.UnsafeExt = childStyle("video")(t:_*)
    def ul(t: ToStyle*): Style.UnsafeExt = childStyle("ul")(t:_*)
    def u(t: ToStyle*): Style.UnsafeExt = childStyle("u")(t:_*)
    def td(t: ToStyle*): Style.UnsafeExt = childStyle("td")(t:_*)
    def tr(t: ToStyle*): Style.UnsafeExt = childStyle("tr")(t:_*)
    def title(t: ToStyle*): Style.UnsafeExt = childStyle("title")(t:_*)
    def time(t: ToStyle*): Style.UnsafeExt = childStyle("time")(t:_*)
    def thead(t: ToStyle*): Style.UnsafeExt = childStyle("thead")(t:_*)
    def th(t: ToStyle*): Style.UnsafeExt = childStyle("th")(t:_*)
    def tfoot(t: ToStyle*): Style.UnsafeExt = childStyle("tfoot")(t:_*)
    def textarea(t: ToStyle*): Style.UnsafeExt = childStyle("textarea")(t:_*)
    def tbody(t: ToStyle*): Style.UnsafeExt = childStyle("tbody")(t:_*)
    def table(t: ToStyle*): Style.UnsafeExt = childStyle("table")(t:_*)
    def sup(t: ToStyle*): Style.UnsafeExt = childStyle("sup")(t:_*)
    def sub(t: ToStyle*): Style.UnsafeExt = childStyle("sub")(t:_*)
    def style(t: ToStyle*): Style.UnsafeExt = childStyle("style")(t:_*)
    def strong(t: ToStyle*): Style.UnsafeExt = childStyle("strong")(t:_*)
    def strike(t: ToStyle*): Style.UnsafeExt = childStyle("strike")(t:_*)
    def span(t: ToStyle*): Style.UnsafeExt = childStyle("span")(t:_*)
    def source(t: ToStyle*): Style.UnsafeExt = childStyle("source")(t:_*)
    def small(t: ToStyle*): Style.UnsafeExt = childStyle("small")(t:_*)
    def select(t: ToStyle*): Style.UnsafeExt = childStyle("select")(t:_*)
    def section(t: ToStyle*): Style.UnsafeExt = childStyle("section")(t:_*)
    def script(t: ToStyle*): Style.UnsafeExt = childStyle("script")(t:_*)
    def samp(t: ToStyle*): Style.UnsafeExt = childStyle("samp")(t:_*)
    def s(t: ToStyle*): Style.UnsafeExt = childStyle("s")(t:_*)
    def q(t: ToStyle*): Style.UnsafeExt = childStyle("q")(t:_*)
    def progress(t: ToStyle*): Style.UnsafeExt = childStyle("progress")(t:_*)
    def pre(t: ToStyle*): Style.UnsafeExt = childStyle("pre")(t:_*)
    def param(t: ToStyle*): Style.UnsafeExt = childStyle("param")(t:_*)
    def p(t: ToStyle*): Style.UnsafeExt = childStyle("p")(t:_*)
    def option(t: ToStyle*): Style.UnsafeExt = childStyle("option")(t:_*)
    def optgroup(t: ToStyle*): Style.UnsafeExt = childStyle("optgroup")(t:_*)
    def ol(t: ToStyle*): Style.UnsafeExt = childStyle("ol")(t:_*)
    def noscript(t: ToStyle*): Style.UnsafeExt = childStyle("noscript")(t:_*)
    def nav(t: ToStyle*): Style.UnsafeExt = childStyle("nav")(t:_*)
    def meter(t: ToStyle*): Style.UnsafeExt = childStyle("meter")(t:_*)
    def meta(t: ToStyle*): Style.UnsafeExt = childStyle("meta")(t:_*)
    def mark(t: ToStyle*): Style.UnsafeExt = childStyle("mark")(t:_*)
    def map(t: ToStyle*): Style.UnsafeExt = childStyle("map")(t:_*)
    def main(t: ToStyle*): Style.UnsafeExt = childStyle("main")(t:_*)
    def link(t: ToStyle*): Style.UnsafeExt = childStyle("link")(t:_*)
    def li(t: ToStyle*): Style.UnsafeExt = childStyle("li")(t:_*)
    def legend(t: ToStyle*): Style.UnsafeExt = childStyle("legend")(t:_*)
    def label(t: ToStyle*): Style.UnsafeExt = childStyle("label")(t:_*)
    def kbd(t: ToStyle*): Style.UnsafeExt = childStyle("kbd")(t:_*)
    def ins(t: ToStyle*): Style.UnsafeExt = childStyle("ins")(t:_*)
    def input(t: ToStyle*): Style.UnsafeExt = childStyle("input")(t:_*)
    def img(t: ToStyle*): Style.UnsafeExt = childStyle("img")(t:_*)
    def iframe(t: ToStyle*): Style.UnsafeExt = childStyle("iframe")(t:_*)
    def i(t: ToStyle*): Style.UnsafeExt = childStyle("i")(t:_*)
    def html(t: ToStyle*): Style.UnsafeExt = childStyle("html")(t:_*)
    def hr(t: ToStyle*): Style.UnsafeExt = childStyle("hr")(t:_*)
    def h1toh6(t: ToStyle*): Style.UnsafeExt = childStyle("h1toh6")(t:_*)
    def header(t: ToStyle*): Style.UnsafeExt = childStyle("header")(t:_*)
    def head(t: ToStyle*): Style.UnsafeExt = childStyle("head")(t:_*)
    def frameset(t: ToStyle*): Style.UnsafeExt = childStyle("frameset")(t:_*)
    def frame(t: ToStyle*): Style.UnsafeExt = childStyle("frame")(t:_*)
    def form(t: ToStyle*): Style.UnsafeExt = childStyle("form")(t:_*)
    def footer(t: ToStyle*): Style.UnsafeExt = childStyle("footer")(t:_*)
    def font(t: ToStyle*): Style.UnsafeExt = childStyle("font")(t:_*)
    def figure(t: ToStyle*): Style.UnsafeExt = childStyle("figure")(t:_*)
    def figcaption(t: ToStyle*): Style.UnsafeExt = childStyle("figcaption")(t:_*)
    def fieldset(t: ToStyle*): Style.UnsafeExt = childStyle("fieldset")(t:_*)
    def embed(t: ToStyle*): Style.UnsafeExt = childStyle("embed")(t:_*)
    def em(t: ToStyle*): Style.UnsafeExt = childStyle("em")(t:_*)
    def dt(t: ToStyle*): Style.UnsafeExt = childStyle("dt")(t:_*)
    def dl(t: ToStyle*): Style.UnsafeExt = childStyle("dl")(t:_*)
    def div(t: ToStyle*): Style.UnsafeExt = childStyle("div")(t:_*)
    def dfn(t: ToStyle*): Style.UnsafeExt = childStyle("dfn")(t:_*)
    def del(t: ToStyle*): Style.UnsafeExt = childStyle("del")(t:_*)
    def dd(t: ToStyle*): Style.UnsafeExt = childStyle("dd")(t:_*)
    def datalist(t: ToStyle*): Style.UnsafeExt = childStyle("datalist")(t:_*)
    def colgroup(t: ToStyle*): Style.UnsafeExt = childStyle("colgroup")(t:_*)
    def col(t: ToStyle*): Style.UnsafeExt = childStyle("col")(t:_*)
    def code(t: ToStyle*): Style.UnsafeExt = childStyle("code")(t:_*)
    def cite(t: ToStyle*): Style.UnsafeExt = childStyle("cite")(t:_*)
    def center(t: ToStyle*): Style.UnsafeExt = childStyle("center")(t:_*)
    def caption(t: ToStyle*): Style.UnsafeExt = childStyle("caption")(t:_*)
    def canvas(t: ToStyle*): Style.UnsafeExt = childStyle("canvas")(t:_*)
    def button(t: ToStyle*): Style.UnsafeExt = childStyle("button")(t:_*)
    def br(t: ToStyle*): Style.UnsafeExt = childStyle("br")(t:_*)
    def body(t: ToStyle*): Style.UnsafeExt = childStyle("body")(t:_*)
    def blockquote(t: ToStyle*): Style.UnsafeExt = childStyle("blockquote")(t:_*)
    def big(t: ToStyle*): Style.UnsafeExt = childStyle("big")(t:_*)
    def bdo(t: ToStyle*): Style.UnsafeExt = childStyle("bdo")(t:_*)
    def basefont(t: ToStyle*): Style.UnsafeExt = childStyle("basefont")(t:_*)
    def base(t: ToStyle*): Style.UnsafeExt = childStyle("base")(t:_*)
    def b(t: ToStyle*): Style.UnsafeExt = childStyle("b")(t:_*)
    def audio(t: ToStyle*): Style.UnsafeExt = childStyle("audio")(t:_*)
    def aside(t: ToStyle*): Style.UnsafeExt = childStyle("aside")(t:_*)
    def article(t: ToStyle*): Style.UnsafeExt = childStyle("article")(t:_*)
    def area(t: ToStyle*): Style.UnsafeExt = childStyle("area")(t:_*)
    def applet(t: ToStyle*): Style.UnsafeExt = childStyle("applet")(t:_*)
    def address(t: ToStyle*): Style.UnsafeExt = childStyle("address")(t:_*)
    def acronym(t: ToStyle*): Style.UnsafeExt = childStyle("acronym")(t:_*)
    def abbr(t: ToStyle*): Style.UnsafeExt = childStyle("abbr")(t:_*)
    def a(t: ToStyle*): Style.UnsafeExt = childStyle("a")(t:_*)
  }
}
